version: '3.5'

services:
  io_kiyar_bitter:
    image: io_kiyar_bitter
    container_name: io_kiyar_bitter
    restart: always
    build: .
    ports:
      - '3010:80'
    networks:
      - nginx

networks:
  nginx:
    external:
      name: nginx